name: weeTrade
version: 1.5
authors: [Dubehh, ImFxrin]
main: nl.dubehh.Main
api-version: 1.17
commands:
   Trade:
      description: Trade Command
      usage: /<command>
      aliases: [weeTrade, wTrade, trade]